config:
  concretizer: clingo
  url_fetch_method: curl

  # Install Packages in user's folder
  install_tree:
    root: ~/.spack/opt/spack

  # Cache source files in user's folder
  source_cache: ~/.spack/var/spack/cache
